name: Setup Node.js and Dependencies
description: Common setup for Node.js environment and npm dependencies

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "lts/*"
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci
