name: Setup Node.js and Dependencies
description: Common setup for Node.js environment and npm dependencies

inputs:
  DATABASE_URL:
    description: Database connection string
    required: true

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "lts/*"
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        DATABASE_URL: ${{ inputs.DATABASE_URL }}
