name: autofix.ci

on:
  pull_request:

permissions:
  contents: write

jobs:
  autofix:
    name: Auto-fix Prettier formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check Prettier formatting
        id: prettier-check
        run: npm run format:check
        continue-on-error: true

      - name: Apply Prettier format
        if: steps.prettier-check.outcome == 'failure'
        run: npm run format

      - name: Auto-fix formatting
        if: steps.prettier-check.outcome == 'failure'
        uses: autofix-ci/action@v1
        with:
          commit-message: "style: apply prettier formatting"
